// Sidebar
export const SIDEBAR_VISIBILITY_TOGGLE = "SIDEBAR_VISIBILITY_TOGGLE";
export const SIDEBAR_VISIBILITY_SHOW = "SIDEBAR_VISIBILITY_SHOW";
export const SIDEBAR_VISIBILITY_HIDE = "SIDEBAR_VISIBILITY_HIDE";
export const SIDEBAR_STICKY_TOGGLE = "SIDEBAR_STICKY_TOGGLE";
export const SIDEBAR_STICKY_ENABLE = "SIDEBAR_STICKY_ENABLE";
export const SIDEBAR_STICKY_DISABLE = "SIDEBAR_STICKY_DISABLE";

// Layout
export const LAYOUT_BOXED_TOGGLE = "LAYOUT_BOXED_TOGGLE";
export const LAYOUT_BOXED_ENABLE = "LAYOUT_BOXED_ENABLE";
export const LAYOUT_BOXED_DISABLE = "LAYOUT_BOXED_DISABLE";

// Theme
export const THEME_TOGGLE = "THEME_TOGGLE";

// user login info
export const USER_LOGIN_INFO = "USER_LOGIN_INFO";
export const TOKEN_INFO = "TOKEN_INFO";
export const REMEMBER_ME_INFO = "REMEMBER_ME_INFO";

// users
export const GET_LIST_USER = "GET_LIST_USER";
export const GET_LIST_USER_SELECTED_ROWS = "GET_LIST_USER_SELECTED_ROWS";


export const GET_LIST_VACCINES = "GET_LIST_VACCINES";
export const GET_LIST_VACCINE_SELECTED_ROWS = "GET_LIST_VACCINE_SELECTED_ROWS";
export const GET_LIST_INJECTIONS = "GET_LIST_INJECTIONS;"

export const GET_LIST_LOCATIONS = "GET_LIST_LOCATIONS";
export const GET_LIST_LOCATION_SELECTED_ROWS = "GET_LIST_LOCATION_SELECTED_ROWS";

export const GET_LIST_INJECTION_SELECTED_ROWS = "GET_LIST_INJECTION_SELECTED_ROWS";
